baseURL: https://blog.juanje.net/
title: Blog de Juanje
#copyright: 'Copyright © 2016-{year} Razon Yang. All Rights Reserved.'
copyright: 'Copyright © {year} Juan Jesús Alejo Sillero. Todos los derechos reservados.'
defaultContentLanguage: es
languages:
  es:
    disabled: false
    title: Blog de Juanje
    weight: 1
    languageName: Español
    copyright: Copyright © {year} Juan Jesús Alejo Sillero. Todos los derechos reservados.
    params:
      brand: Blog de Juanje
#      description: Un cajón de sastre en el que compartir mis aprendizajes y descubrimientos
      keywords: Juanje, Blog
  en:
    disabled: false
    title: Juanje's Blog
    weight: 2
    languageName: English
    copyright: Copyright © {year} Juan Jesús Alejo Sillero. All rights reserved.
    params:
      brand: Juanje's Blog
#      description: A catch-all website for sharing my learnings and discoveries
      keywords: Juanje's, Blog
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
pagination:
  pagerSize: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/
  blog: /blog/:year/:month/:title/

module:
  imports:
    - path: github.com/razonyang/hugo-theme-bootstrap
#   proxy: https://goproxy.cn

# services:
#   disqus:
#     shortname: your-disqus-shortname

markup:
  highlight:
    guessSyntax: true
    lineNos: false
    noClasses: false
    lineNumbersInTable: false
